### PR TITLE
Added a Go to Top button

### PR DESCRIPTION
**Pull request by umangrules**
Hi there, there were alot of anchor tags to go to the top of the page so i replaced all of them by this simple button. I hope you like it.

### CODE REVIEW

**Comment by surjithctly** [comment]
Can you show me a working example?

**Comment by umangrules** [comment]
Have a look : [https://umangrules.github.io/](url)

**Comment by umangrules** [comment]
[https://umangrules.github.io/documentation-html-template/](url)

**Comment by umangrules** [comment]
if this does't work then just **type** the above link in new tab

**Comment by surjithctly** [comment]
Thanks again.

1. There are no smooth scrolling effect. Can you add it?
2. Instead of writing Top, may be replace it with icon
3. So that the box can also be little smaller. (its too big right now)

**Comment by umangrules** [comment]
Hi @surjithctly 
I have done all the changes you asked for, hope you like it.

**Comment by surjithctly** [comment]
Thanks again, I found few more issues. 

1. The scrolling part on the left menu is messed up, may be because you have added scroll behavior? If possible, use Javascript
2. Use `fa-chevron-up` as icon as it would look cleaner
3. make sure the icon font-size is no more than `18px`
4. Make sure the button is round not oval. 

Hoping to merge soon!

**Comment by umangrules** [comment]
Hi @surjithctly 
fixed the issues you mentioned.
I hope you like it.

**Comment by surjithctly** [comment]
Awesome. Merging it now.

**Comment by umangrules** [comment]
Can you please add the tag "hacktoberfest-accepted" to my PR.

**Comment by surjithctly** [comment]
Don't worry, This project is already tagged appropriately. 

The tag you are mentioning is for un-merged but approved PRs. Since yours merged, all is good.

**Pull request merged**
