### PR TITLE
indentaion of js; add simple darkmode

### PR DESCRIPTION
**Pull request by ynn1k**

### CODE REVIEW

**Comment by surjithctly** [comment]
Can you show a working example?

**Comment by ynn1k** [comment]
The following are two screenshots from Firefox comparing normal/darmode
Bildschirmfoto am 2020-10-06 um 10 39 19
Bildschirmfoto am 2020-10-06 um 10 39 22

**Comment by surjithctly** [comment]
Looks good. 

Can we use `icon` instead of checkbox? Also it would be cool, if you could publish on GitHub pages or somewhere so I can see everything works as expected.

**Comment by ynn1k** [comment]
i changed the checkbox to a bootstrap3 glyph icon
live preview: https://yannik.dev/documentation-html-template/
currently there is a bug with `.docs-sidebar` I have no clue why the css filter property is affecting it... I will look into it later.

**Comment by ynn1k** [comment]
should be fixed :)

**Comment by surjithctly** [comment]
I think the best position would be Top right without text. So that the icon toggles from Sun to Moon on click.

**Comment by ynn1k** [comment]
Okay, I will work on it when I get home later today

**Comment by ynn1k** [comment]
updated the preview

**Comment by surjithctly** [comment]
Thanks. I'm seeing a different issue now. Browser is taking some time to repaint the dark-mode, thus causing performance issue. Since its a long single page. invert seems not performant. 

Any ideas to tackle this?

**Comment by ynn1k** [comment]
I have no device on which I can reproduce a performance issue. Right now I can't think of a quick way to solve this 🤔

**Comment by ynn1k** [comment]
just noticed that the button were behind the content 🛠

**Comment by surjithctly** [comment]
Here's what I meant: https://www.loom.com/share/41e40bca77f6442681c99fb42c62b98c

**Comment by ynn1k** [comment]
Okay, i see. but this repaint issue is not occurring on any of my devices 🤔
A possible solution could be to overwrite all colors based on the `<html>` `.dark` class. Maybe I'll give it a try tonight.

**Comment by ynn1k** [comment]
repaint issue should be solved now. updated preview.

**Comment by surjithctly** [comment]
Looks great now. Can I ask more more quick thing? 

Just remove the background and box shadow of the icon. So that it looks subtle.. the current grey seems perfect for both mode. 

Thanks again for your hard work 😊

**Comment by ynn1k** [comment]
Yup, no problem. its done.

**Comment by surjithctly** [comment]
Done! Merged 🥂🎉

**Pull request merged**
